export default{
Home_url:("https://consumersenergymanagement.ca/about-us/"),
About_url:("https://consumersenergymanagement.ca/about-us/"),
Products_url:("https://consumersenergymanagement.ca/products/"),
Services_url:("https://consumersenergymanagement.ca/services/"),
Tools_url:("https://consumersenergymanagement.ca/tools-resources/"),
Promotions_url:("https://consumersenergymanagement.ca/promotions/"),
Careers_url:("https://consumersenergymanagement.ca/careers/"),
Blog_url:("https://consumersenergymanagement.ca/blog/"),
FAQs_url:("https://consumersenergymanagement.ca/faq/"),
Contact_url:("https://consumersenergymanagement.ca/contact-us/"),
Home_menu:('#menu-item-31 > a'),
About_menu:('#menu-item-36 > a'),
Products_menu:('#menu-item-32 > [href="products/"]'),
Services_menu:('#menu-item-34 > [href="services/"]'),
Tools_menu:('#menu-item-35 > [href="tools-resources/"]'),
Promotions_menu:('#menu-item-673 > a'),
Career_menu:('#menu-item-1589 > a'),
Blog_menu:('#menu-item-1725 > a'),
FAQs_menu:('#menu-item-1727 > a'),
Contact_menu:('#menu-item-1726 > a'),
Savings_calculator:('https://consumersenergymanagement.ca/savings-calculator/'),
Step1Box:('#step1box'),
Step2Box:('#step2box'),
Step3Box:('#step3box'),
State:('[name="nastates"]'),
City:('[name="stage2"]'),
Stories:(':nth-child(6) > :nth-child(2) > .Slcst'),
Square_Feet:(':nth-child(6) > :nth-child(3) > .Slcst'),
Years:('.Txtss'),
Price_column:('#step1col3'),
Gas:('#step1col3 > :nth-child(1) > input'),
Propane:('[name="propaneGas"]'),
Oil:('#step1col3 > :nth-child(3) > input'),
Summer:('#step1col3 > :nth-child(4) > input'),
Winter:('#step1col3 > :nth-child(5) > input'),
CurrentHeatingSystem:('#step2col2 > :nth-child(1)'),
EfficiencyLevel_CS:('#step2col2 > :nth-child(2)'),
NewHeatingSystem:('#step2col2 > :nth-child(3) > p'),
EfficiencyLevel_NS:('#step2col2 > :nth-child(4)'),
Heat_type:('#heattype'),
Efficiency_HeatType:('#eheattype'),
New_Heater:(':nth-child(3) > p > .Slcst'),
Efficiency_New:('#newheateff > p > .Slcst'),
Annual_Heating_Savings:('#step2col3 > :nth-child(1)'),
AHS:('#AHS'),
Current_Heating_Cost:('#step2col3 > :nth-child(3)'),
CHC:('#CHC'),
New_heating_Cost:('#step2col3 > :nth-child(5)'),
NHC:('#NHC'),
HSPF:('#voldhspf')


}